### ISSUE TITLE
Docker 0.5.0 image fails to start with certificate error

### ISSUE THREAD

**Issue by Ranbato** [zerotier/zeronsd#189]
Reverting back to 0.4.3 fixes the issue.
```
 docker logs -f zeronsd                                                                          [2022-05-18 08:33:22 MDT] 
May 18 14:33:22.648  INFO zeronsd::init: Welcome to ZeroNS!
Error: Communication Error error sending request for url (https://my.zerotier.com/api/v1/network/asdf): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (unable to get local issuer certificate)

Caused by:
    0: error sending request for url (https://my.zerotier.com/api/v1/network/asdf): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (unable to get local issuer certificate)
    1: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (unable to get local issuer certificate)
    2: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (unable to get local issuer certificate)
    3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914:
May 18 14:33:27.044  INFO zeronsd::init: Welcome to ZeroNS!
Error: Communication Error error sending request for url (https://my.zerotier.com/api/v1/network/asdf): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (unable to get local issuer certificate)

Caused by:
    0: error sending request for url (https://my.zerotier.com/api/v1/network/asdf): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (unable to get local issuer certificate)
    1: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (unable to get local issuer certificate)
    2: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (unable to get local issuer certificate)
    3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914:
^C

```

**Comment by erikh** [comment]
Thanks for the heads up, I'll look into this today.

------- Original Message -------

**Comment by erikh** [comment]
0.5.2 should resolve this. Sorry for the delay. reopen this issue if you see more trouble, please.

**Comment by Ranbato** [comment]
I'm still seeing the container failing on start with latest or 0.5.2.  I'm not getting any logs all though so I'm going to see if I can do some troubleshooting.

**Comment by Ranbato** [comment]
OK, I have narrowed it down to the Alpine image.  Other image works fine for me.  I'm pretty busy for the next while, but might be able to do additional troubleshooting next week.  LMK if you want me to reopen this issue or start a new one.

**Comment by erikh** [comment]
No, this is fine. Thanks!!

------- Original Message -------

**Comment by erikh** [comment]
lemme look at it. sorry about this!

------- Original Message -------
